CREATE TABLE locations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  country VARCHAR(255) DEFAULT NULL,
  eus_contact VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL
) ENGINE=INNODB default charset=utf8;
