CREATE TABLE `incidents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` char(1) DEFAULT NULL COMMENT '1=Open, 2=Closed',
  `number` char(7) DEFAULT NULL,
  `environment` varchar(255) DEFAULT NULL COMMENT 'DEV, QA, UAT, PROD',
  `location_id` int NOT NULL,
  `ci_tier` char(1) DEFAULT NULL COMMENT '1,2,3',
  `severity` char(1) DEFAULT NULL COMMENT '1,2,3,4',
  `business_impact` varchar(255) DEFAULT NULL,
  `summary` text,
  `group_id` int NOT NULL,
  `bridge` varchar(255) DEFAULT NULL,
  `current_status` text,
  `source_id` int NOT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `coordinator1_id` int NOT NULL,
  `coordinator2_id` int NOT NULL,
  `coordinator3_id` int NOT NULL,
  foreign key (`location_id`) references `locations` (`id`),
  foreign key (`group_id`) references `groups` (`id`),
  foreign key (`source_id`) references `sources` (`id`),
  foreign key (`coordinator1_id`) references `employees` (`id`),
  foreign key (`coordinator2_id`) references `employees` (`id`),
  foreign key (`coordinator3_id`) references `employees` (`id`),
  PRIMARY KEY (`id`)
);