CREATE TABLE incidents (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status enum ('Resolved', 'Open'),
    number char(10),
    environment enum ('UAT', 'QA', 'PROD', 'DEV'),
    location_id INT NOT NULL,
    ci_tier enum ('1', '2', '3'),
    severity enum ('1', '2', '3', '4'),
    impact varchar(255),
    detection_id INT NOT NULL,
    summary text,
    rgroup_id INT NOT NULL,
    bridge text,
    current_status text,
    source_id INT NOT NULL,
    start_date datetime,
    end_date datetime,
    coordinator1_id INT NOT NULL,
    coordinator2_id INT NOT NULL,
    coordinator3_id INT NOT NULL,
    FOREIGN KEY (location_id) REFERENCES locations(id),
    FOREIGN KEY (detection_id) REFERENCES detections(id),
    FOREIGN KEY (rgroup_id) REFERENCES rgroups(id),
    FOREIGN KEY (source_id) REFERENCES sources(id),
    FOREIGN KEY (coordinator1_id) REFERENCES employees(id),
    FOREIGN KEY (coordinator2_id) REFERENCES employees(id),
    FOREIGN KEY (coordinator3_id) REFERENCES employees(id)
)